export interface ReporteDinamicoAlertas {
    fechaNotificacion:                           Date;
    fechaResolucion:                             null;
    notificaciones:                              number;
    nnaId:                                       number;
    primerNombre:                                string;
    segundoNombre:                               string;
    primerApellido:                              string;
    segundoApellido:                             string;
    edad:                                        number;
    diagnosticoId:                               number;
    diagnostico:                                 string;
    residenciaActualTelefono:                    null;
    residenciaActualMunicipioId:                 string;
    residenciaActualMunicipio:                   string | null;
    residenciaActualDepartamento:                string | null;
    residenciaActualDireccion:                   null | string;
    trasladosQuienAsumioCostosTraslado:          null | string;
    trasladosQuienAsumioCostosVivienda:          null | string;
    tratamientoHaDejadodeAsistir:                boolean | null;
    tipoSeguimiento:                             string;
    agente:                                      string | null;
    epsId:                                       number;
    eps:                                         null;
    cuidadorEmail:                               null | string;
    tratamientoCuantoTiemposinAsistir:           number | null;
    tratamientoUnidadMedidaIdTiempoId:           null | string;
    tratamientoUnidadMedidaTiempo:               null | string;
    tratamientoCausasInasistenciaId:             string;
    tratamientoCausasInasistencia:               string;
    tratamientoCausasInasistenciaOtra:           null;
    categoriaAlerta:                             string;
    subCategoriaAlerta:                          string;
    estadoAlerta:                                string;
    tratamientoEstudiaActualmente:               boolean | null;
    tratamientoHaDejadodeAsistirColegio:         boolean | null;
    tratamientoTiempoInasistenciaColegio:        number | null;
    tratamientoTiempoInasistenciaUnidadMedidaId: null | string;
    tratamientoTiempoInasistenciaUnidadMedida:   null | string;
    fechaRespuesta:                              Date;
    respuestaEntidad:                            string;
    tratamientoHaSidoInformadoClaramente:        boolean | null;
    trasladosHaSidoTrasladadodeInstitucion:      boolean | null;
    trasladosHaSolicitadoApoyoFundacion:         boolean | null;
    trasladosNombreFundacion:                    null | string;
    trasladosApoyoRecibidoxFundacion:            null | string;
}