export interface ReporteDetalleNuevoDepurados {
    id:                           number;
    idReporteDepuracion:          number;
    fechaNotificacion:            Date;
    origenReporteId:              number;
    origenReporte:                string;
    primerNombre:                 string;
    segundoNombre:                string;
    primerApellido:               string;
    segundoApellido:              string;
    diagnosticoId:                number;
    diagnostico:                  string;
    fechaNacimiento:              Date;
    edad:                         number;
    sexoId:                       string;
    sexo:                         string;
    tipoIdentificacionId:         string;
    tipoIdentificacion:           string;
    numeroIdentificacion:         string;
    paisId:                       string;
    pais:                         string;
    etniaId:                      string;
    etnia:                        string;
    municipioNacimientoId:        string;
    departamentoNacimiento:       null;
    municipioNacimiento:          null;
    grupoPoblacionId:             string;
    grupoPoblacion:               string;
    residenciaOrigenMunicipioId:  string;
    residenciaOrigenDepartamento: null;
    residenciaOrigenMunicipio:    null;
    residenciaOrigenBarrio:       string;
    residenciaOrigenAreaId:       string;
    areaProcedencia:              string;
    residenciaOrigenDireccion:    string;
    residenciaOrigenEstratoId:    string;
    residenciaActualTelefono:     string;
    departamentoTratamientoId:    string;
    departamentoTratamiento:      null | string;
    estadoIngresoEstrategiaId:    number;
    estadoIngresoEstrategia:      string;
    fechaIngresoEstrategia:       Date;
    tipoRegimenSSId:              string;
    tipoRegimenSS:                string;
    epsId:                        number;
    eps:                          null;
    ipsId:                        number;
    ips:                          null;
    cuidadorNombres:              string;
    cuidadorParentescoId:         number;
    cuidadorParentesco:           string;
    cuidadorEmail:                string;
    cuidadorTelefono:             string;
    agente:                       null | string;
    estadoNNAId:                  number | null;
    estado:                       string | null;
}
