export interface ReporteDinamicoNNA {
  id:                           number;
  primerNombre:                 string;
  segundoNombre:                string;
  primerApellido:               string;
  segundoApellido:              string;
  diagnosticoId:                number;
  diagnostico:                  string;
  fechaNacimiento:              Date;
  edad:                         number;
  sexoId:                       string;
  sexo:                         string;
  tipoIdentificacionId:         string;
  tipoIdentificacion:           string;
  numeroIdentificacion:         string;
  fechaNotificacionSIVIGILA:    Date;
  origenReporteId:              number;
  origenReporte:                string;
  paisId:                       string;
  pais:                         string;
  etniaId:                      string;
  etnia:                        string;
  municipioNacimientoId:        null | string;
  departamentoNacimiento:       null | string;
  municipioNacimiento:          null | string;
  grupoPoblacionId:             string;
  grupoPoblacion:               string;
  residenciaOrigenMunicipioId:  string;
  residenciaOrigenDepartamento: null | string;
  residenciaOrigenMunicipio:    null | string;
  residenciaOrigenBarrio:       string;
  residenciaOrigenAreaId:       string;
  areaProcedencia:              string;
  residenciaOrigenDireccion:    string;
  residenciaOrigenEstratoId:    string;
  residenciaActualTelefono:     null | string;
  residenciaActualMunicipioId:  string;
  municipioResidenciaActual:    null | string;
  departamentoResidenciaActual: null | string;
  estadoIngresoEstrategiaId:    number;
  estadoIngresoEstrategia:      string;
  fechaIngresoEstrategia:       Date;
  tipoRegimenSSId:              string;
  tipoRegimenSS:                null | string;
  epsId:                        number;
  eps:                          null;
  ipsId:                        number | null;
  ips:                          null | string;
  cuidadorNombres:              null | string;
  cuidadorParentescoId:         number | null;
  cuidadorParentesco:           string;
  cuidadorEmail:                null | string;
  cuidadorTelefono:             string;
  tipoSeguimiento:              string;
}
