export interface ReporteDinamicoSeguimiento {
    tipoSeguimiento:                        string;
    asunto:                                 string;     
    seguimientoId:                          number;
    nnaId:                                  number;
    primerNombre:                           string;
    segundoNombre:                          string;
    primerApellido:                         string;
    segundoApellido:                        string;
    diagnosticoId:                          number;
    diagnostico:                            string;
    tipoIdentificacionId:                   string;
    tipoIdentificacion:                     string;
    numeroIdentificacion:                   string;
    tipoRegimenSSId:                        string;
    tipoRegimenSS:                          string | null;
    eapbId:                                 number | null;
    eapb:                                   null;
    estadoId:                               number;
    estado:                                 string;
    fechaConsultaDiagnostico:               Date;
    fechaDiagnostico:                       Date;
    motivoNoDiagnosticoId:                  number | null;
    motivoNoDiagnostico:                    string;
    motivoNoDiagnosticoOtro:                null | string;
    fechaInicioTratamiento:                 Date | null;
    ipsId:                                  number | null;
    ips:                                    null | string;
    recaida:                                boolean;
    cantidadRecaidas:                       number | null;
    fechaUltimaRecaida:                     Date | null;
    trasladosHaSidoTrasladadodeInstitucion: boolean | null;
    residenciaActualMunicipioId:            string;
    residenciaActualMunicipio:              string | null;
    residenciaActualDepartamento:           null | string;
    residenciaActualBarrio:                 null | string;
    residenciaActualAreaId:                 null | string;
    residenciaActualArea:                   string;
    residenciaActualDireccion:              null | string;
    residenciaActualEstratoId:              null | string;
    trasladoTieneCapacidadEconomica:        boolean | null;
    trasladoEAPBSuministroApoyo:            boolean | null;
    trasladosServiciosdeApoyoOportunos:     boolean | null;
    cuidadorNombres:                        null | string;
    cuidadorParentescoId:                   number | null;
    cuidadorParentesco:                     string;
    cuidadorEmail:                          null | string;
    cuidadorTelefono:                       string;
    fechaSeguimiento:                       Date;
    observacionesSolicitante:               string;
    observacionAgente:                      null | string;
}
