server {
    listen 80;
    server_name localhost;

    # Incluir MIME types por defecto + fuentes
    include /etc/nginx/mime.types;
    types {
        font/woff2  woff2;
        font/woff   woff;
    }

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Fuentes - sin gzip y con CORS
    location ~* \.(woff2?|ttf|otf|eot)$ {
        root /usr/share/nginx/html;
        add_header Access-Control-Allow-Origin *;
        gzip off;
        expires 30d;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
